package msg

const (
	ZONE_KW               = "zone"
	RECURSIVE_OPR_KW      = "recursiveOpr"
	FORCE_FLAG_KW         = "forceFlag"
	BULK_OPR_KW           = "bulkOpr"
	DEST_RESC_NAME_KW     = "destRescName"
	DATA_TYPE_KW          = "dataType"
	DATA_SIZE_KW          = "dataSize"
	NUM_THREADS_KW        = "numThreads"
	OPR_TYPE_KW           = "oprType"
	UPDATE_REPL_KW        = "updateRepl"
	RESC_NAME_KW          = "rescName"
	COPIES_KW             = "copies"
	AGE_KW                = "age"
	ADMIN_KW              = "irodsAdmin"
	COLLECTION_TYPE_KW    = "collectionType"
	LOCK_TYPE_KW          = "lockType"
	LOCK_CMD_KW           = "lockCmd"
	LOCK_FD_KW            = "lockFd"
	RESC_HIER_STR_KW      = "resc_hier"
	REPLICA_TOKEN_KW      = "replicaToken"
	DEST_RESC_HIER_STR_KW = "dest_resc_hier"
	IN_PDMO_KW            = "in_pdmo"
	STAGE_OBJ_KW          = "stage_object"
	SYNC_OBJ_KW           = "sync_object"
	IN_REPL_KW            = "in_repl"
)
