package api

// Shared string constants for tests in package api. Defined to satisfy the
// goconst linter for repeated literals.
const (
	testStr           = "test"
	testTestPath      = "/test"
	testUser          = "user"
	testRodsUser      = "rodsuser"
	testHello         = "hello"
	testGeneric       = "generic"
	testChecksum      = "checksum"
	testDemoResc      = "demoResc"
	testResc1         = "resc1"
	testResc2         = "resc2"
	testDemoRescResc1 = "demoResc;resc1"
	testDemoRescResc2 = "demoResc;resc2"
	testCollName      = "coll_name"
	testTestZone      = "testZone"
	testReplicaNumber = "replica_number"
	testResourceHier  = "resource_hierarchy"
	testKey           = "key"
	testUnit          = "unit"
	testOwn           = "own"
	testZoneHome      = "/zone/home"
	testZone          = "/zone"
	testZoneShort     = "zone"
	testZone1         = "zone1"
	testFileTxt       = "file.txt"
	testFile1Txt      = "file1.txt"
	testFile2Txt      = "file2.txt"
	testZoneHomeFile  = "/zone/home/file.txt"
	testZoneHomeSub   = "/zone/home/sub/file.txt"
	testPath1         = "/path1"
	testPath2         = "/path2"
	testABPath        = "/a/b"
	testUsername      = "username"
	testValue         = "value"
	testStringType    = "string"
)
